name: medi_genie
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  animations: ^2.0.11
  animated_snack_bar: ^0.4.0
  audioplayers: ^6.1.0
  auto_size_text: 3.0.0
  card_swiper: ^3.0.1
  cached_network_image: 3.3.0
  custom_radio_grouped_button:
    path: packages/custom_radio_grouped_button
  dio: ^5.7.0
  device_info_plus: ^10.1.2
  easy_localization: 3.0.7
  easy_localization_loader: 2.0.0
  equatable: 2.0.5
  fetch_client: ^1.1.2
  fl_chart: ^0.69.0
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.1
  flutter_chat_ui: ^1.6.15
  flutter_downloader: ^1.11.8
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: 0.13.1
  flutter_local_notifications: ^17.2.2
  flutter_native_splash: ^2.4.1
  flutter_secure_storage: ^9.2.2
  flutter_screenutil: 5.9.3
  flutter_spinkit: 5.2.1
  flutter_sticky_header: ^0.6.5
  flutter_svg: 2.0.10+1
  flutter_lints : ^4.0.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  get: ^5.0.0-release-candidate-9.2
  go_router: 14.2.7
  google_fonts: 6.2.1
  google_sign_in: ^6.2.1
  grouped_list: ^6.0.0
  group_button: ^5.3.4
  http: ^1.2.2
  image_picker: ^1.1.2
  json_path: 0.7.4
  logger: 2.4.0
  material_text_fields: ^1.0.5
  mime_type: 1.0.1
  page_transition: 2.1.0
  path_provider: 2.1.4
  platform_device_id: ^1.0.1
  provider: 6.1.2
  rflutter_alert: ^2.0.7
  scroll_date_picker: ^3.8.0
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.2
  sleek_circular_slider: ^2.0.1
  smooth_page_indicator: ^1.2.0+3
  sqflite: 2.3.3+1
  timeago: 3.7.0
  timer_count_down: ^2.2.2
  url_launcher: 6.3.0
  uuid: ^4.5.0
  video_player: ^2.9.1
  web_browser_detect: ^2.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  easy_localization_generator: ^0.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/imageicon/
    - assets/images/icon/
    - assets/audios/
    - assets/langs/

  fonts:
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
